// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHM9JHA_HPhFp33ythKkbKQPWPsHFJjTU',
    appId: '1:148536360935:web:86c9b6f3ca7ca4dbee0742',
    messagingSenderId: '148536360935',
    projectId: 'adhan-ahmadiyya',
    authDomain: 'adhan-ahmadiyya.firebaseapp.com',
    storageBucket: 'adhan-ahmadiyya.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2vC7XMLyzkf_Eb3DEGuuO2su9zI8P7LI',
    appId: '1:148536360935:android:7e4e41f0463be80bee0742',
    messagingSenderId: '148536360935',
    projectId: 'adhan-ahmadiyya',
    storageBucket: 'adhan-ahmadiyya.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3xfijkN7B0bHDa2roQXvqORY49o7mZKs',
    appId: '1:148536360935:ios:462d5a8482ddbec0ee0742',
    messagingSenderId: '148536360935',
    projectId: 'adhan-ahmadiyya',
    storageBucket: 'adhan-ahmadiyya.firebasestorage.app',
    iosBundleId: 'org.tarish.adhan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3xfijkN7B0bHDa2roQXvqORY49o7mZKs',
    appId: '1:148536360935:ios:462d5a8482ddbec0ee0742',
    messagingSenderId: '148536360935',
    projectId: 'adhan-ahmadiyya',
    storageBucket: 'adhan-ahmadiyya.firebasestorage.app',
    iosBundleId: 'org.tarish.adhan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHM9JHA_HPhFp33ythKkbKQPWPsHFJjTU',
    appId: '1:148536360935:web:34e6881725270d40ee0742',
    messagingSenderId: '148536360935',
    projectId: 'adhan-ahmadiyya',
    authDomain: 'adhan-ahmadiyya.firebaseapp.com',
    storageBucket: 'adhan-ahmadiyya.firebasestorage.app',
  );
}
